/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/cats": {
    get: operations["AppController_getCats"];
    post: operations["AppController_updateCat"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CatEntity: {
      id: number;
      name: string;
      age: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  AppController_getCats: {
    responses: {
      200: {
        content: {
          "application/json": (components["schemas"]["CatEntity"])[];
        };
      };
    };
  };
  AppController_updateCat: {
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["CatEntity"];
        };
      };
    };
  };
}
